### ISSUE TITLE
Change color scheme of "other" so that is not the same as "fossil fuels"

### ISSUE THREAD

**Issue by yhan178** [UBC-MDS/DSCI-532_2024_6_Green-Development-Planner#100]

**Comment by joeywwwu** [comment]
Change color scheme of "other" so that is not the same as "fossil fuels" at https://github.com/UBC-MDS/DSCI-532_2024_6_Green-Development-Planner/pull/98

**Comment by yhan178** [comment]
Change of the color scheme for the two pie charts: see 7cc1cd07aac5c381adb7a927ca1f7e5b0ad6d962
