### ISSUE TITLE
Feedback to Address

### ISSUE THREAD

**Issue by ianm99** [UBC-MDS/DSCI-532_2024_6_Green-Development-Planner#86]
- [x] Add short description of the data and the dashboard's purpose to the dashboard itself. (Ian)
- [x] Add percent symbols to the tooltip display for arc charts (Joey)
- [x] Adjust width of title splashboard. (Joey)
- [x] Prevent order of country vs average bars from flipping (Ian)
- [x] Adjust arc chart colours: not beige also fossil fuel does not equal Other (Haley)

**Comment by phchen5** [comment]
Final Touches:
- [x] nothing shows up during initial startup of app
- [x] add favicon and tab title
- [x] update gif
- [x] update readme
- [x] tooltip formatting
- [x] bar chart alignment?
- [x] update deployment date
- [x] title/subtitle formatting
