### ISSUE TITLE
Add percent symbols to the tooltip display for arc charts

### ISSUE THREAD

**Issue by joeywwwu** [UBC-MDS/DSCI-532_2024_6_Green-Development-Planner#90]

**Comment by joeywwwu** [comment]
![image](https://github.com/UBC-MDS/DSCI-532_2024_6_Green-Development-Planner/assets/143630759/65613c0a-1d8c-4677-8c61-73d8d1b01d94)
![image](https://github.com/UBC-MDS/DSCI-532_2024_6_Green-Development-Planner/assets/143630759/1ae0e691-8e17-4d4a-9c2a-819489e1689f)
![image](https://github.com/UBC-MDS/DSCI-532_2024_6_Green-Development-Planner/assets/143630759/8c3a6979-7ce2-42d8-aa85-6b21aeec220a)

Hey Team, so far, I've already cleaned data and used new cleaned data for pie charts to accelerate our online data loading speed. The 'energy consumption' chart works well with add %, **however, the percentages displayed on the 'electricity pie chart' do not correspond with the actual data, FYI**. After a couple of hours of debugging, and trying different solutions, I realize it really exceeds my current skills and expertise on data viz. Please feel free to run the dashboard on this branch, I genuinely need you guys' help with this issue. Thanks a lot!! 

If it still doesn't work out, I would advise deleting % symbols for both pie charts, but keeping percentage info in tooltips (when users want to look at the percentage, they move their mouse on pie charts ),  for better artistic effects.

**Comment by yhan178** [comment]
Hi Joey, I don't think it is necessary to have those numbers with our bar charts, as long as we can see the percent symbols in the tooltip display (i.e., when you hover on the corresponding arc) it should be okay.

**Comment by joeywwwu** [comment]
@yhan178 Ah, I see! Thanks for clarifying!
